# Ejercicio de Groupby

In [ ]:
import pandas as pd

In [ ]:
path = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'
users = pd.read_csv(path, sep='|', index_col='user_id')
print(users.shape)
users.head()

(943, 4)

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

## ¿Cuántas ocupaciones diferentes hay en este conjunto de datos?

In [ ]:
users.occupation.unique(),users.occupation.unique().shape

(array(['technician', 'other', 'writer', 'executive', 'administrator',
        'student', 'lawyer', 'educator', 'scientist', 'entertainment',
        'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
        'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
       dtype=object), (21,))

## ¿Cuál es la ocupación más frecuente?

In [ ]:
users.occupation.value_counts()

student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: occupation, dtype: int64

In [ ]:
users.occupation.mode()

0    student
dtype: object

## ¿Cuál es la edad media por ocupación?

In [ ]:
users.groupby('occupation').mean().sort_values(by='age')

                     age
occupation
student        22.081633
none           26.555556
entertainment  29.222222
artist         31.392857
homemaker      32.571429
programmer     33.121212
technician     33.148148
other          34.523810
scientist      35.548387
salesman       35.666667
writer         36.311111
engineer       36.388060
lawyer         36.750000
marketing      37.615385
executive      38.718750
administrator  38.746835
librarian      40.000000
healthcare     41.562500
educator       42.010526
doctor         43.571429
retired        63.071429

## Para cada ocupación calcule las edades mínimas y máximas.

In [ ]:
users.groupby('occupation').agg({'age':['max','min']})

              age
              max min
occupation
administrator  70  21
artist         48  19
doctor         64  28
educator       63  23
engineer       70  22
entertainment  50  15
executive      69  22
healthcare     62  22
homemaker      50  20
lawyer         53  21
librarian      69  23
marketing      55  24
none           55  11
other          64  13
programmer     63  20
retired        73  51
salesman       66  18
scientist      55  23
student        42   7
technician     55  21
writer         60  18

## Para cada combinación de ocupación y género calcule la edad media.

In [ ]:
users.groupby(['occupation','gender']).mean()

                            age
occupation    gender
administrator F       40.638889
              M       37.162791
artist        F       30.307692
              M       32.333333
doctor        M       43.571429
educator      F       39.115385
              M       43.101449
engineer      F       29.500000
              M       36.600000
entertainment F       31.000000
              M       29.000000
executive     F       44.000000
              M       38.172414
healthcare    F       39.818182
              M       45.400000
homemaker     F       34.166667
              M       23.000000
lawyer        F       39.500000
              M       36.200000
librarian     F       40.000000
              M       40.000000
marketing     F       37.200000
              M       37.875000
none          F       36.500000
              M       18.600000
other         F       35.472222
              M       34.028986
programmer    F       32.166667
              M       33.216667
retired       F       70.000000
              M       62.538462
salesman      F       27.000000
              M       38.555556
scientist     F       28.333333
              M       36.321429
student       F       20.750000
              M       22.669118
technician    F       38.000000
              M       32.961538
writer        F       37.631579
              M       35.346154

## Para cada ocupación muestre el porcentaje de mujeres y hombres.

In [ ]:
users.groupby(['occupation','gender']).count()

                      age  zip_code
occupation    gender
administrator F        36        36
              M        43        43
artist        F        13        13
              M        15        15
doctor        M         7         7
educator      F        26        26
              M        69        69
engineer      F         2         2
              M        65        65
entertainment F         2         2
              M        16        16
executive     F         3         3
              M        29        29
healthcare    F        11        11
              M         5         5
homemaker     F         6         6
              M         1         1
lawyer        F         2         2
              M        10        10
librarian     F        29        29
              M        22        22
marketing     F        10        10
              M        16        16
none          F         4         4
              M         5         5
other         F        36        36
              M        69        69
programmer    F         6         6
              M        60        60
retired       F         1         1
              M        13        13
salesman      F         3         3
              M         9         9
scientist     F         3         3
              M        28        28
student       F        60        60
              M       136       136
technician    F         1         1
              M        26        26
writer        F        19        19
              M        26        26

In [ ]:
users_pivot = users.pivot_table('age',index='occupation',columns='gender',aggfunc='count',margins=True).fillna(0)

In [ ]:
users_pivot['All']

occupation
administrator     79
artist            28
doctor             7
educator          95
engineer          67
entertainment     18
executive         32
healthcare        16
homemaker          7
lawyer            12
librarian         51
marketing         26
none               9
other            105
programmer        66
retired           14
salesman          12
scientist         31
student          196
technician        27
writer            45
All              943
Name: All, dtype: int64

In [ ]:
op1 = users_pivot.apply(lambda x: x*100/users_pivot['All'])
op1

gender                 F           M    All
occupation
administrator  45.569620   54.430380  100.0
artist         46.428571   53.571429  100.0
doctor          0.000000  100.000000  100.0
educator       27.368421   72.631579  100.0
engineer        2.985075   97.014925  100.0
entertainment  11.111111   88.888889  100.0
executive       9.375000   90.625000  100.0
healthcare     68.750000   31.250000  100.0
homemaker      85.714286   14.285714  100.0
lawyer         16.666667   83.333333  100.0
librarian      56.862745   43.137255  100.0
marketing      38.461538   61.538462  100.0
none           44.444444   55.555556  100.0
other          34.285714   65.714286  100.0
programmer      9.090909   90.909091  100.0
retired         7.142857   92.857143  100.0
salesman       25.000000   75.000000  100.0
scientist       9.677419   90.322581  100.0
student        30.612245   69.387755  100.0
technician      3.703704   96.296296  100.0
writer         42.222222   57.777778  100.0
All            28.950159   71.049841  100.0

In [ ]:
total_occupation = users.groupby('occupation').count()[['age']]
for_gender = users.groupby(['occupation','gender']).count()[['age']]
op2 = for_gender.div(total_occupation,level='occupation')*100
op2

                             age
occupation    gender
administrator F        45.569620
              M        54.430380
artist        F        46.428571
              M        53.571429
doctor        M       100.000000
educator      F        27.368421
              M        72.631579
engineer      F         2.985075
              M        97.014925
entertainment F        11.111111
              M        88.888889
executive     F         9.375000
              M        90.625000
healthcare    F        68.750000
              M        31.250000
homemaker     F        85.714286
              M        14.285714
lawyer        F        16.666667
              M        83.333333
librarian     F        56.862745
              M        43.137255
marketing     F        38.461538
              M        61.538462
none          F        44.444444
              M        55.555556
other         F        34.285714
              M        65.714286
programmer    F         9.090909
              M        90.909091
retired       F         7.142857
              M        92.857143
salesman      F        25.000000
              M        75.000000
scientist     F         9.677419
              M        90.322581
student       F        30.612245
              M        69.387755
technician    F         3.703704
              M        96.296296
writer        F        42.222222
              M        57.777778

## Descubra la proporción de hombres por ocupación y clasifíquela de mayor a menor

In [ ]:
op1['M'].sort_values(ascending=False)

occupation
doctor           100.000000
engineer          97.014925
technician        96.296296
retired           92.857143
programmer        90.909091
executive         90.625000
scientist         90.322581
entertainment     88.888889
lawyer            83.333333
salesman          75.000000
educator          72.631579
All               71.049841
student           69.387755
other             65.714286
marketing         61.538462
writer            57.777778
none              55.555556
administrator     54.430380
artist            53.571429
librarian         43.137255
healthcare        31.250000
homemaker         14.285714
Name: M, dtype: float64

In [ ]:
op2.loc[[(c,'M') for c in op2.index.get_level_values(0)]]

                             age
occupation    gender
administrator M        54.430380
              M        54.430380
artist        M        53.571429
              M        53.571429
doctor        M       100.000000
educator      M        72.631579
              M        72.631579
engineer      M        97.014925
              M        97.014925
entertainment M        88.888889
              M        88.888889
executive     M        90.625000
              M        90.625000
healthcare    M        31.250000
              M        31.250000
homemaker     M        14.285714
              M        14.285714
lawyer        M        83.333333
              M        83.333333
librarian     M        43.137255
              M        43.137255
marketing     M        61.538462
              M        61.538462
none          M        55.555556
              M        55.555556
other         M        65.714286
              M        65.714286
programmer    M        90.909091
              M        90.909091
retired       M        92.857143
              M        92.857143
salesman      M        75.000000
              M        75.000000
scientist     M        90.322581
              M        90.322581
student       M        69.387755
              M        69.387755
technician    M        96.296296
              M        96.296296
writer        M        57.777778
              M        57.777778

In [ ]:
op2.query("gender=='M'").sort_values(by='age',ascending=False)

                             age
occupation    gender
doctor        M       100.000000
engineer      M        97.014925
technician    M        96.296296
retired       M        92.857143
programmer    M        90.909091
executive     M        90.625000
scientist     M        90.322581
entertainment M        88.888889
lawyer        M        83.333333
salesman      M        75.000000
educator      M        72.631579
student       M        69.387755
other         M        65.714286
marketing     M        61.538462
writer        M        57.777778
none          M        55.555556
administrator M        54.430380
artist        M        53.571429
librarian     M        43.137255
healthcare    M        31.250000
homemaker     M        14.285714